# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3711b4e32842f841c62d15bc231a49b18c9b237894731a34ba4d996dde9ab102a5fa080ab8764fdcd1b0fdb8d784a62f0b6aa0b9b223b29aadf2368fec226ea5

test:
  secret_key_base: 1e7b291efbcf0a83a10baf0c386dbfaca4c57038505955981653bcc310695a23d4368babb629bcd90d1db3bc31e9e31196d40458be280299bdbe297ddb1436af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
